# Generated by Django 4.2.4 on 2023-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_changed', models.JSONField()),
                ('changed_by', models.CharField(max_length=50)),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('message', models.TextField()),
            ],
        ),
    ]
