# Generated by Django 4.2.4 on 2023-09-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationauditlog',
            name='object_type',
            field=models.CharField(default='unknown_type_pre_release', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationauditlog',
            name='object_changed',
            field=models.CharField(max_length=60),
        ),
    ]
