# Generated by Django 4.2.4 on 2023-08-06 06:07

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ib_toolkit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.CharField(max_length=50)),
                ('application_environment', models.CharField(max_length=5)),
                ('network', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_cidr', message='Enter a valid CIDR notation (e.g., 192.168.0.0/24).', regex='^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2}$')])),
                ('infoblox_ref', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='datacenternetworkblock',
            options={'verbose_name': 'Datacenter Network Block', 'verbose_name_plural': 'Datacenter Network Blocks'},
        ),
    ]
