# Generated by Django 4.2.4 on 2023-08-06 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_toolkit', '0002_network_alter_datacenternetworkblock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='datacenter_name',
            field=models.CharField(default='azc_use1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='created_by',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_character', message='Only alphanumeric characters and underscores are allowed.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
